apiVersion: v1
kind: Secret
metadata:
  name: nexuspay-secrets
  namespace: nexuspay
type: Opaque
stringData:
  DB_USER: "nexus_admin"
  DB_PASSWORD: "NexusSecurePassword2026!"
  JWT_SECRET: "nexuspay-super-secret-jwt-key-for-pci-dss-compliance"
  OPENAI_API_KEY: "mock-openai-key-finops"
  AWS_ACCESS_KEY_ID: "mock-aws-key"
  AWS_SECRET_ACCESS_KEY: "mock-aws-secret"
